const heroNames = [
  'Endeavor',
  'Hawks',
  'Best Jeanist',
  'Edgeshot',
  'Mirko',
  'Kamui Woods',
  'Wash',
  'Ryukyu',
  'Gang Orca',
  'Shishido',
  'Mt. Lady',
  'Fat Gum',
  'Manual',
  'Mandalay',
  'Pixie-Bob',
  'Tiger',
  'Airjet',
  'Backdraft',
  'Cementoss',
  'Centipeder',
  'Crimson Riot',
  'Ectoplasm',
  'Eraser Head',
  'Fourth Kind',
  'Gran Torino',
  'Gunhead',
  'Hound Dog',
  'Kesagiri Man',
  'Lunch Rush',
  'Mr. Brave',
  'Ms. Joke',
  'Power Loader',
  'Present Mic',
  'Rock Lock',
  'Selkie',
  'Slugger',
  'Snipe',
  'Takeshita',
  'The Fly',
  'Thirteen',
  'Thirteen',
  'Toy-Toy',
  'Uwabami',
  'Vlad King',
  'Blackbelt',
  'Odd-Eye',
  'Death Arms',
  'Gyges',
  'Briareos',
  'Crust',
  'Majestic',
  'Master Driller',
  'Funkman',
  'Midnight',
  'Native',
  'X-Less',
  'Eel Boy',
  "Slidin' Go",
  'Nighteye',
  'Snatch',
  'All Might',
  'Ragdoll',
  'Ingenium',
  'Compass Kid',
  "O'Clock",
  'Lady Nagant',
  'Water Hose',
  'Nana',
  'Smoke-Eater',
  'Lariat',
  'Anima',
  'Battle Fist',
  'Boomerang Man',
  "Can't Stop Twinkling",
  'Cellophane',
  'Chargebolt',
  'Chewyee',
  'Comicman',
  'Creati',
  'Deku',
  'Dynamight',
  'Earphone Jack',
  'Emily',
  'Froppy',
  'Gale Force',
  'Grand',
  'Gevaudan',
  'Grape Juice',
  'Illus-o-Camie',
  'Ingenium',
  'Invisible Girl',
  'Jack Mantis',
  'Lemillion',
  'Lizardy',
  'Long Weizi',
  'Lucky Strike',
  'Mines',
  'Mr. Smith',
  'Mudman',
  'Nejire Chan',
  'Phantom Thief',
  'Pinky',
  'Plamo',
  'Real Steel',
  'Red Riot',
  'Rocketti',
  'Rule',
  'Shemage',
  'Sensor Girl',
  'Shoto',
  'Shishikross',
  'Spiral',
  'Sugarman',
  'Suneater',
  'Tailman',
  'Tentacole',
  'Tsuburaba',
  'Tsukuyomi',
  'Turtle Neck',
  'Uravity',
  'Vantablack',
  'Vine',
  'Welder',
];

/**
 * Função para criar um nome de herói falso
 * @returns {string} Retorna um nome de herói com indexador aleatório
 */
function fakeName(): string {
  const randomName = heroNames[Math.floor(Math.random() * heroNames.length)];
  const randomString = Math.random().toString(36).substring(2, 7);
  return `${randomName.toUpperCase()}${randomString}`
    .replace(' ', '')
    .replace('-', '')
    .trim();
}

export default fakeName;
